### ISSUE TITLE
Proposed change in description of repo.

### ISSUE THREAD

**Issue by melodykramer** [18F/docker-elasticsearch#8]
Hey!

I'm doing a quick audit of all of 18F's GitHub repos to make sure that descriptions, ReadMe's, and issues are written as concisely and descriptively as they can be. This will help other organizations who would like to adapt our code as well as the public — who may be interested in adapting our code or contributing to our repos.

No rush, but when you have a second, could you add a description of this repo? It can be one sentence or a phrase.

Mel

**Comment by ozzyjohnson** [comment]
All done!
